# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Build and Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
 run:
  working-directory: ./FrontEndv2.0/quasar-project

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Install essential packages
        run: yarn --silent install
      - name: Install quasar
        run: yarn global add @quasar/cli
      - name: build
        run: quasar build
      - name: Run tests
        run: yarn test
      - name: Run eslint check
        run: yarn run lint

